packages:
  - "apps/*"
  - "packages/*"
catalog:
  "@types/node": ^24.7.0
  "@types/react": ^19.2.2
  "@types/react-dom": ^19.2.1
  react: ^19.2.0
  react-dom: ^19.2.0
  tsup: ^8.5.0
  terser: ^5.44.0
  typescript: ^5.9.3
  vitest: ^3.2.4
